# Generated by Django 5.2 on 2025-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('dob', models.DateField()),
                ('aadhar', models.PositiveBigIntegerField(unique=True)),
                ('address', models.TextField()),
                ('account_type', models.CharField(max_length=32)),
                ('account_number', models.BigAutoField(default=1234567890, primary_key=True, serialize=False)),
                ('pin', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=5000)),
            ],
        ),
    ]
