# Generated by Django 5.2 on 2025-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
